export default {
  VOICE_ICON: require('../static/images/voice-icon.png'),
  WELCOME_BACKGROUND: require('../static/images/splash.jpg'),
  HOME_ICON: require('../static/images/home-icon.png'),
  COMPASS_ICON: require('../static/images/compass-icon.png'),
  EVENTS_ICON: require('../static/images/events-icon.png'),
  MY_TRIP_ICON: require('../static/images/my-trip-icon.png'),
  MORE_ICON: require('../static/images/more-icon.png'),
  FILTER_ICON: require('../static/images/filter-icon.png'),
  HOME_BACKGROUND: require('../static/images/home-bg.png'),

  TRAVELLING_WITH_OWN: require('../static/images/personalization/own.jpg'),
  TRAVELLING_WITH_PARTNER: require('../static/images/personalization/partner.jpg'),
  TRAVELLING_WITH_FRIENDS: require('../static/images/personalization/friends.jpg'),
  TRAVELLING_WITH_FAMILY: require('../static/images/personalization/family.jpg'),

  LOGO: require('../static/images/logo.png'),

  REGION_ICON: require('../static/images/region-icon.png'),

  CATEGORY_NATURE: require('../static/images/categories/nature.jpg'),
  CATEGORY_DINING: require('../static/images/categories/dining.jpg'),
  CATEGORY_CULTURE: require('../static/images/categories/culture.jpg'),
  CATEGORY_THEMED_ATTRACTIONS: require('../static/images/categories/themed_attractions.jpg'),
  CATEGORY_SPORT: require('../static/images/categories/sport.jpg'),
  CATEGORY_SIGHTSEEING: require('../static/images/categories/sight-seeing.jpg'),
  CATEGORY_SHOWS: require('../static/images/categories/shows.jpg'),
  CATEGORY_SHOPPING: require('../static/images/categories/shopping.jpg'),
  CATEGORY_DIGITAL: require('../static/images/categories/digital.jpg'),
  CATEGORY_CONVENTIONS: require('../static/images/categories/conventions.jpg'),

  CONTACT_HOTLINE: require('../static/images/contact/hotline.jpg'),

  MAP_PIN_LOCATION_SHOWS: require('../static/images/map/location-shows.png'),
  MAP_PIN_LOCATION_CULTURE: require('../static/images/map/location-culture.png'),
  MAP_PIN_LOCATION_NATURE: require('../static/images/map/location-nature.png'),
  MAP_PIN_LOCATION_SIGHTSEEING: require('../static/images/map/location-sightseeing.png'),
  MAP_PIN_LOCATION_THEMED_ATTRACTIONS: require('../static/images/map/location-themed-attractions.png'),
  MAP_PIN_LOCATION_DIGITAL: require('../static/images/map/location-digital.png'),
  MAP_PIN_LOCATION_DINING: require('../static/images/map/location-dining.png'),
  MAP_PIN_LOCATION_SHOPPING: require('../static/images/map/location-shopping.png'),
  MAP_PIN_LOCATION_SPORT: require('../static/images/map/location-sport.png'),
  MAP_PIN_LOCATION_CONVENTIONS: require('../static/images/map/location-conventions.png'),

  MAP_PIN_EVENT_SHOWS: require('../static/images/map/event-shows.png'),
  MAP_PIN_EVENT_CULTURE: require('../static/images/map/event-culture.png'),
  MAP_PIN_EVENT_NATURE: require('../static/images/map/event-nature.png'),
  MAP_PIN_EVENT_SIGHTSEEING: require('../static/images/map/event-sightseeing.png'),
  MAP_PIN_EVENT_THEMED_ATTRACTIONS: require('../static/images/map/event-themed-attractions.png'),
  MAP_PIN_EVENT_DIGITAL: require('../static/images/map/event-digital.png'),
  MAP_PIN_EVENT_DINING: require('../static/images/map/event-dining.png'),
  MAP_PIN_EVENT_SHOPPING: require('../static/images/map/event-shopping.png'),
  MAP_PIN_EVENT_SPORT: require('../static/images/map/event-sport.png'),
  MAP_PIN_EVENT_CONVENTIONS: require('../static/images/map/event-conventions.png'),

  CONTACT_PHONE_PROVIDER_1: require('../static/images/contact/phone-provider-1.jpg'),
  CONTACT_PHONE_PROVIDER_2: require('../static/images/contact/phone-provider-2.jpg'),
  CONTACT_PHONE_PROVIDER_3: require('../static/images/contact/phone-provider-3.jpg'),
  LOADER: require('../static/images/loader.gif'),
};
